# Generated by Django 4.2.4 on 2023-08-02 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_diaria', models.IntegerField(max_length=5)),
                ('consumo', models.IntegerField(default=0, max_length=5)),
                ('data', models.DateField(default=datetime.datetime(2023, 8, 2, 17, 5, 56, 305454))),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('peso', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoDeConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agua.consumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agua.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.usuario'),
        ),
    ]
