# Generated by Django 4.2.4 on 2023-08-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='consumo',
            field=models.IntegerField(choices=[(250, 250), (350, 350), (500, 500)]),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='meta_diaria',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='HistoricoDeConsumo',
        ),
    ]
