# Generated by Django 4.2.4 on 2023-08-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_alter_consumo_consumo_alter_consumo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='meta_consumida',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='data',
            field=models.DateField(editable=False),
        ),
    ]
