# Generated by Django 4.2.4 on 2023-08-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_consumo_meta_consumida_alter_consumo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='percentual_consumido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
